name: So, does it work?

on: [push]

jobs:
  build:
    strategy:
      matrix:
        python-version: [ '3.5' ]
        os: [ 'windows-latest', 'macos-latest' ]

        #, '3.6', '3.7', '3.8'
        #'ubuntu-latest', 

    runs-on: ${{ matrix.os }}

    name: Python ${{ matrix.python-version }} on ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v1

      - name: Update submodules
        run: |
          git submodule init
          git submodule update

      - name: Setup python
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python-version }}
          architecture: x64

      - name: Install requirements
        run: python -m pip install -Ur requirements.txt

      - name: Compile project
        run: make

      - name: Run JSON5 tests suite
        run: python run-tests.py

      - name: Run "JSON is a Minefield" suite
        run: python run-minefield-test.py
